defmodule Viban.Repo.Migrations.AddHookSystem do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :worktree_path, :text
      add :worktree_branch, :text
    end

    create table(:repositories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :path, :text, null: false
      add :default_branch, :text, default: "main"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :board_id,
          references(:boards,
            column: :id,
            name: "repositories_board_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create table(:hooks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :command, :text, null: false
      add :cleanup_command, :text
      add :working_directory, :text, default: "worktree"
      add :timeout_ms, :bigint, default: 30000

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :board_id,
          references(:boards,
            column: :id,
            name: "hooks_board_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create table(:column_hooks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :hook_type, :text, null: false
      add :position, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :column_id,
          references(:columns,
            column: :id,
            name: "column_hooks_column_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :hook_id,
          references(:hooks,
            column: :id,
            name: "column_hooks_hook_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:column_hooks, "column_hooks_column_id_fkey")

    drop constraint(:column_hooks, "column_hooks_hook_id_fkey")

    drop table(:column_hooks)

    drop constraint(:hooks, "hooks_board_id_fkey")

    drop table(:hooks)

    drop constraint(:repositories, "repositories_board_id_fkey")

    drop table(:repositories)

    alter table(:tasks) do
      remove :worktree_branch
      remove :worktree_path
    end
  end
end
