defmodule Viban.Repo.Migrations.AddInProgressToTasks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :in_progress, :boolean, default: false
    end
  end

  def down do
    alter table(:tasks) do
      remove :in_progress
    end
  end
end
