defmodule Viban.Repo.Migrations.AddCustomBranchName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :custom_branch_name, :text
    end
  end

  def down do
    alter table(:tasks) do
      remove :custom_branch_name
    end
  end
end
