defmodule Viban.Repo.Migrations.Phase3LlmIntegration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :agent_status, :text, default: "idle"
      add :agent_status_message, :text
    end

    create table(:messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false
      add :content, :text, null: false
      add :status, :text, default: "pending"
      add :metadata, :map, default: %{}
      add :sequence, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :task_id,
          references(:tasks,
            column: :id,
            name: "messages_task_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:messages, "messages_task_id_fkey")

    drop table(:messages)

    alter table(:tasks) do
      remove :agent_status_message
      remove :agent_status
    end
  end
end
