defmodule Viban.Repo.Migrations.AddTaskQueueFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :queued_at, :utc_datetime
      add :queue_priority, :bigint, default: 0
    end

    # Index for efficient queue ordering
    create index(:tasks, [:column_id, :queue_priority, :queued_at])
  end

  def down do
    drop index(:tasks, [:column_id, :queue_priority, :queued_at])

    alter table(:tasks) do
      remove :queue_priority
      remove :queued_at
    end
  end
end
