defmodule Viban.Repo.Migrations.AddKanbanResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tasks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :position, :bigint, null: false, default: 0
      add :priority, :text, default: "medium"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :column_id, :uuid, null: false
    end

    create table(:columns, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:tasks) do
      modify :column_id,
             references(:columns,
               column: :id,
               name: "tasks_column_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:columns) do
      add :name, :text, null: false
      add :position, :bigint, null: false, default: 0
      add :color, :text, default: "#6366f1"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :board_id, :uuid, null: false
    end

    create table(:boards, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:columns) do
      modify :board_id,
             references(:boards,
               column: :id,
               name: "columns_board_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:boards) do
      add :name, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:boards) do
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :name
    end

    drop constraint(:columns, "columns_board_id_fkey")

    alter table(:columns) do
      modify :board_id, :uuid
    end

    drop table(:boards)

    alter table(:columns) do
      remove :board_id
      remove :updated_at
      remove :inserted_at
      remove :color
      remove :position
      remove :name
    end

    drop constraint(:tasks, "tasks_column_id_fkey")

    alter table(:tasks) do
      modify :column_id, :uuid
    end

    drop table(:columns)

    drop table(:tasks)
  end
end
