defmodule Viban.Repo.Migrations.AddPrFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :pr_url, :text
      add :pr_number, :bigint
      add :pr_status, :text
    end

    create index(:tasks, [:pr_number])
  end

  def down do
    drop index(:tasks, [:pr_number])

    alter table(:tasks) do
      remove :pr_status
      remove :pr_number
      remove :pr_url
    end
  end
end
