defmodule Viban.Repo.Migrations.CreateExecutorSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:executor_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :executor_type, :text, null: false
      add :prompt, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :exit_code, :bigint
      add :error_message, :text
      add :working_directory, :text
      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :task_id,
          references(:tasks,
            column: :id,
            name: "executor_sessions_task_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:executor_sessions, "executor_sessions_task_id_fkey")

    drop table(:executor_sessions)
  end
end
