defmodule Viban.Repo.Migrations.UnifyTaskEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Note: hook_history, hook_queue were already removed and message_queue already added
    # in a previous migration. The alter block is removed.

    # Drop old tables that are being consolidated into task_events
    drop_if_exists table(:executor_messages)
    drop_if_exists table(:executor_sessions)
    drop_if_exists table(:messages)
    drop_if_exists table(:hook_executions)

    create table(:task_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false
      add :status, :text
      add :role, :text
      add :content, :text
      add :hook_name, :text
      add :hook_id, :text
      add :hook_settings, :map, default: %{}
      add :skip_reason, :text
      add :error_message, :text
      add :queued_at, :utc_datetime_usec
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :triggering_column_id, :uuid
      add :executor_type, :text
      add :prompt, :text
      add :exit_code, :bigint
      add :working_directory, :text
      add :session_id, :uuid
      add :sequence, :bigint
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :task_id,
          references(:tasks,
            column: :id,
            name: "task_events_task_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :column_hook_id,
          references(:column_hooks,
            column: :id,
            name: "task_events_column_hook_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    # Add indexes for efficient queries
    create index(:task_events, [:task_id, :inserted_at])
    create index(:task_events, [:task_id, :type])
    create index(:task_events, [:session_id], where: "session_id IS NOT NULL")
  end

  def down do
    drop_if_exists index(:task_events, [:session_id])
    drop_if_exists index(:task_events, [:task_id, :type])
    drop_if_exists index(:task_events, [:task_id, :inserted_at])

    drop constraint(:task_events, "task_events_task_id_fkey")
    drop constraint(:task_events, "task_events_column_hook_id_fkey")

    drop table(:task_events)

    # Recreate old tables (schema only, data is lost)
    create table(:messages, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :task_id, references(:tasks, type: :uuid, on_delete: :delete_all), null: false
      add :role, :text, null: false
      add :content, :text, null: false
      add :status, :text
      add :metadata, :map, default: %{}
      add :sequence, :bigint, null: false
      timestamps()
    end

    create table(:hook_executions, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :task_id, references(:tasks, type: :uuid, on_delete: :delete_all), null: false
      add :hook_name, :text, null: false
      add :hook_id, :text, null: false
      add :status, :text, null: false
      add :hook_settings, :map, default: %{}
      add :queued_at, :utc_datetime_usec, null: false
      timestamps()
    end

    create table(:executor_sessions, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :task_id, references(:tasks, type: :uuid, on_delete: :delete_all), null: false
      add :executor_type, :text, null: false
      add :prompt, :text, null: false
      add :status, :text, null: false
      timestamps()
    end

    create table(:executor_messages, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :session_id, references(:executor_sessions, type: :uuid, on_delete: :delete_all), null: false
      add :role, :text, null: false
      add :content, :text, null: false
      add :metadata, :map, default: %{}
      add :inserted_at, :utc_datetime_usec, null: false
    end
  end
end
