defmodule Viban.Repo.Migrations.AddWorktreeUniqueConstraint do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:tasks, [:worktree_path], name: "tasks_unique_worktree_path_index")

    alter table(:repositories) do
      modify :clone_url, :text, null: true
      modify :full_name, :text, null: true
      modify :provider_repo_id, :text, null: true
      modify :provider, :text, default: "local"
    end

    create unique_index(:repositories, [:board_id, :local_path],
             name: "repositories_unique_local_path_per_board_index"
           )
  end

  def down do
    drop_if_exists unique_index(:repositories, [:board_id, :local_path],
                     name: "repositories_unique_local_path_per_board_index"
                   )

    alter table(:repositories) do
      modify :provider, :text, default: nil
      modify :provider_repo_id, :text, null: false
      modify :full_name, :text, null: false
      modify :clone_url, :text, null: false
    end

    drop_if_exists unique_index(:tasks, [:worktree_path],
                     name: "tasks_unique_worktree_path_index"
                   )
  end
end
