defmodule Viban.Repo.Migrations.AddRemovableToColumnHooks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:column_hooks) do
      add :removable, :boolean, default: true
    end
  end

  def down do
    alter table(:column_hooks) do
      remove :removable
    end
  end
end
