defmodule Viban.Repo.Migrations.InitialSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false
      add :provider_uid, :text, null: false
      add :provider_login, :text, null: false
      add :name, :text
      add :email, :text
      add :avatar_url, :text
      add :access_token, :text, null: false
      add :token_expires_at, :utc_datetime
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:provider, :provider_uid], name: "users_unique_provider_uid_index")

    create table(:test_messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :text, :text, null: false, default: "Hello from Viban!"
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:tasks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :position, :float, null: false, default: 0.0
      add :priority, :text, default: "medium"
      add :description_images, {:array, :map}, default: []
      add :worktree_path, :text
      add :worktree_branch, :text
      add :custom_branch_name, :text
      add :agent_status, :text, default: "idle"
      add :agent_status_message, :text
      add :in_progress, :boolean, default: false
      add :error_message, :text
      add :queued_at, :utc_datetime
      add :queue_priority, :bigint, default: 0
      add :pr_url, :text
      add :pr_number, :bigint
      add :pr_status, :text
      add :is_parent, :boolean, default: false
      add :subtask_position, :bigint, default: 0
      add :subtask_generation_status, :text
      add :executed_hooks, {:array, :text}, default: []
      add :message_queue, {:array, :map}, default: []
      add :auto_start, :boolean, null: false, default: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :column_id, :uuid, null: false
      add :parent_task_id, :uuid
      add :periodical_task_id, :uuid
    end

    create table(:task_templates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description_template, :text
      add :position, :bigint, null: false, default: 0
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :board_id, :uuid, null: false
    end

    create table(:task_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false
      add :status, :text
      add :role, :text
      add :content, :text
      add :hook_name, :text
      add :hook_id, :text
      add :hook_settings, :map, default: %{}
      add :skip_reason, :text
      add :error_message, :text
      add :queued_at, :utc_datetime_usec
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :triggering_column_id, :uuid
      add :executor_type, :text
      add :prompt, :text
      add :exit_code, :bigint
      add :working_directory, :text
      add :session_id, :uuid
      add :sequence, :bigint
      add :metadata, :map, default: %{}
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :task_id,
          references(:tasks,
            column: :id,
            name: "task_events_task_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :column_hook_id, :uuid
    end

    create table(:repositories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false, default: "local"
      add :provider_repo_id, :text
      add :name, :text, null: false
      add :full_name, :text
      add :clone_url, :text
      add :html_url, :text
      add :default_branch, :text, default: "main"
      add :local_path, :text
      add :clone_status, :text, default: "pending"
      add :clone_error, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :board_id, :uuid, null: false
    end

    create table(:periodical_tasks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :schedule, :text, null: false
      add :executor, :text, default: "claude_code"
      add :execution_count, :bigint, null: false, default: 0
      add :last_executed_at, :utc_datetime_usec
      add :next_execution_at, :utc_datetime_usec
      add :enabled, :boolean, null: false, default: true
      add :last_created_task_id, :uuid
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :board_id, :uuid, null: false
    end

    create table(:hooks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :hook_kind, :text, null: false, default: "script"
      add :command, :text
      add :agent_prompt, :text
      add :agent_executor, :text, default: "claude_code"
      add :agent_auto_approve, :boolean, default: false
      add :default_execute_once, :boolean, default: false
      add :default_transparent, :boolean, default: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :board_id, :uuid, null: false
    end

    create table(:columns, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:tasks) do
      modify :column_id, references(:columns, column: :id, name: "tasks_column_id_fkey", type: :uuid, prefix: "public")

      modify :parent_task_id,
             references(:tasks,
               column: :id,
               name: "tasks_parent_task_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :periodical_task_id,
             references(:periodical_tasks,
               column: :id,
               name: "tasks_periodical_task_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:tasks, [:worktree_path], name: "tasks_unique_worktree_path_index")

    alter table(:columns) do
      add :name, :text, null: false
      add :position, :bigint, null: false, default: 0
      add :color, :text, default: "#6366f1"
      add :settings, :map, default: %{}
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :board_id, :uuid, null: false
    end

    create table(:column_hooks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:task_events) do
      modify :column_hook_id,
             references(:column_hooks,
               column: :id,
               name: "task_events_column_hook_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:column_hooks) do
      add :hook_id, :text, null: false
      add :hook_type, :text, null: false, default: "on_entry"
      add :position, :bigint, default: 0
      add :execute_once, :boolean, default: false
      add :hook_settings, :map, default: %{}
      add :transparent, :boolean, default: false
      add :removable, :boolean, default: true
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :column_id,
          references(:columns, column: :id, name: "column_hooks_column_id_fkey", type: :uuid, prefix: "public"),
          null: false
    end

    create unique_index(:column_hooks, [:column_id, :hook_id], name: "column_hooks_unique_hook_per_column_index")

    create table(:boards, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:task_templates) do
      modify :board_id,
             references(:boards, column: :id, name: "task_templates_board_id_fkey", type: :uuid, prefix: "public")
    end

    alter table(:repositories) do
      modify :board_id,
             references(:boards, column: :id, name: "repositories_board_id_fkey", type: :uuid, prefix: "public")
    end

    create unique_index(:repositories, [:board_id, :local_path], name: "repositories_unique_local_path_per_board_index")

    create unique_index(:repositories, [:board_id, :provider, :provider_repo_id],
             name: "repositories_unique_repo_per_board_index"
           )

    alter table(:periodical_tasks) do
      modify :board_id,
             references(:boards, column: :id, name: "periodical_tasks_board_id_fkey", type: :uuid, prefix: "public")
    end

    alter table(:hooks) do
      modify :board_id, references(:boards, column: :id, name: "hooks_board_id_fkey", type: :uuid, prefix: "public")
    end

    create unique_index(:hooks, [:board_id, :name], name: "hooks_unique_name_per_board_index")

    alter table(:columns) do
      modify :board_id, references(:boards, column: :id, name: "columns_board_id_fkey", type: :uuid, prefix: "public")
    end

    create unique_index(:columns, [:board_id, :name], name: "columns_unique_name_per_board_index")

    create unique_index(:columns, [:board_id, :position], name: "columns_unique_position_per_board_index")

    alter table(:boards) do
      add :name, :text, null: false
      add :description, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, references(:users, column: :id, name: "boards_user_id_fkey", type: :uuid, prefix: "public"),
        null: false
    end

    create unique_index(:boards, [:user_id, :name], name: "boards_unique_name_per_user_index")

    create table(:actor_states, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :actor_type, :text, null: false
      add :actor_id, :text, null: false
      add :state, :map, null: false, default: %{}
      add :status, :text, null: false, default: "starting"
      add :message, :text
      add :version, :bigint, null: false, default: 1
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:actor_states, [:actor_type, :actor_id], name: "actor_states_unique_actor_index")
  end

  def down do
    drop_if_exists unique_index(:actor_states, [:actor_type, :actor_id], name: "actor_states_unique_actor_index")

    drop table(:actor_states)

    drop_if_exists unique_index(:boards, [:user_id, :name], name: "boards_unique_name_per_user_index")

    drop constraint(:boards, "boards_user_id_fkey")

    alter table(:boards) do
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :name
    end

    drop_if_exists unique_index(:columns, [:board_id, :position], name: "columns_unique_position_per_board_index")

    drop_if_exists unique_index(:columns, [:board_id, :name], name: "columns_unique_name_per_board_index")

    drop constraint(:columns, "columns_board_id_fkey")

    alter table(:columns) do
      modify :board_id, :uuid
    end

    drop_if_exists unique_index(:hooks, [:board_id, :name], name: "hooks_unique_name_per_board_index")

    drop constraint(:hooks, "hooks_board_id_fkey")

    alter table(:hooks) do
      modify :board_id, :uuid
    end

    drop constraint(:periodical_tasks, "periodical_tasks_board_id_fkey")

    alter table(:periodical_tasks) do
      modify :board_id, :uuid
    end

    drop_if_exists unique_index(:repositories, [:board_id, :provider, :provider_repo_id],
                     name: "repositories_unique_repo_per_board_index"
                   )

    drop_if_exists unique_index(:repositories, [:board_id, :local_path],
                     name: "repositories_unique_local_path_per_board_index"
                   )

    drop constraint(:repositories, "repositories_board_id_fkey")

    alter table(:repositories) do
      modify :board_id, :uuid
    end

    drop constraint(:task_templates, "task_templates_board_id_fkey")

    alter table(:task_templates) do
      modify :board_id, :uuid
    end

    drop table(:boards)

    drop_if_exists unique_index(:column_hooks, [:column_id, :hook_id], name: "column_hooks_unique_hook_per_column_index")

    drop constraint(:column_hooks, "column_hooks_column_id_fkey")

    alter table(:column_hooks) do
      remove :column_id
      remove :updated_at
      remove :inserted_at
      remove :removable
      remove :transparent
      remove :hook_settings
      remove :execute_once
      remove :position
      remove :hook_type
      remove :hook_id
    end

    drop constraint(:task_events, "task_events_column_hook_id_fkey")

    alter table(:task_events) do
      modify :column_hook_id, :uuid
    end

    drop table(:column_hooks)

    alter table(:columns) do
      remove :board_id
      remove :updated_at
      remove :inserted_at
      remove :settings
      remove :color
      remove :position
      remove :name
    end

    drop_if_exists unique_index(:tasks, [:worktree_path], name: "tasks_unique_worktree_path_index")

    drop constraint(:tasks, "tasks_column_id_fkey")

    drop constraint(:tasks, "tasks_parent_task_id_fkey")

    drop constraint(:tasks, "tasks_periodical_task_id_fkey")

    alter table(:tasks) do
      modify :periodical_task_id, :uuid
      modify :parent_task_id, :uuid
      modify :column_id, :uuid
    end

    drop table(:columns)

    drop table(:hooks)

    drop table(:periodical_tasks)

    drop table(:repositories)

    drop constraint(:task_events, "task_events_task_id_fkey")

    drop table(:task_events)

    drop table(:task_templates)

    drop table(:tasks)

    drop table(:test_messages)

    drop_if_exists unique_index(:users, [:provider, :provider_uid], name: "users_unique_provider_uid_index")

    drop table(:users)
  end
end
