defmodule Viban.Repo.Migrations.AddHookDefaults do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:hooks) do
      add :default_execute_once, :boolean, default: false
      add :default_transparent, :boolean, default: false
    end
  end

  def down do
    alter table(:hooks) do
      remove :default_transparent
      remove :default_execute_once
    end
  end
end
