defmodule Viban.Repo.Migrations.CreateActorStates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:actor_states, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :actor_type, :text, null: false
      add :actor_id, :text, null: false
      add :state, :map, null: false, default: %{}
      add :status, :text, null: false, default: "starting"
      add :message, :text
      add :version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:actor_states, [:actor_type, :actor_id],
             name: "actor_states_unique_actor_index"
           )
  end

  def down do
    drop_if_exists unique_index(:actor_states, [:actor_type, :actor_id],
                     name: "actor_states_unique_actor_index"
                   )

    drop table(:actor_states)
  end
end
