defmodule Viban.Repo.Migrations.AddCascadeDeletes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:tasks, "tasks_parent_task_id_fkey")

    alter table(:tasks) do
      modify :parent_task_id,
             references(:tasks,
               column: :id,
               name: "tasks_parent_task_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:messages, "messages_task_id_fkey")

    alter table(:messages) do
      modify :task_id,
             references(:tasks,
               column: :id,
               name: "messages_task_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:executor_sessions, "executor_sessions_task_id_fkey")

    alter table(:executor_sessions) do
      modify :task_id,
             references(:tasks,
               column: :id,
               name: "executor_sessions_task_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:executor_messages, "executor_messages_session_id_fkey")

    alter table(:executor_messages) do
      modify :session_id,
             references(:executor_sessions,
               column: :id,
               name: "executor_messages_session_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:executor_messages, "executor_messages_session_id_fkey")

    alter table(:executor_messages) do
      modify :session_id,
             references(:executor_sessions,
               column: :id,
               name: "executor_messages_session_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:executor_sessions, "executor_sessions_task_id_fkey")

    alter table(:executor_sessions) do
      modify :task_id,
             references(:tasks,
               column: :id,
               name: "executor_sessions_task_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:messages, "messages_task_id_fkey")

    alter table(:messages) do
      modify :task_id,
             references(:tasks,
               column: :id,
               name: "messages_task_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:tasks, "tasks_parent_task_id_fkey")

    alter table(:tasks) do
      modify :parent_task_id,
             references(:tasks,
               column: :id,
               name: "tasks_parent_task_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
