defmodule Viban.Repo.Migrations.T do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      modify :position, :float, default: 0.0
    end
  end

  def down do
    alter table(:tasks) do
      modify :position, :decimal, default: "0"
    end
  end
end
